[theme]
primaryColor = "#5c7359"
backgroundColor = "#f6f7f6"
secondaryBackgroundColor = "#e3e7e3"
textColor = "#3d3d3d"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = true